export interface Product {
  id: number;
  name: string;
  brand: string;
  category: string;
  musd: number;
  tag: string;
  description: string;
  images: string[];
  colors?: string[];
  sizes?: string[];
}

export const PRODUCTS: Product[] = [
  {
    id: 1,
    name: 'Phantom Runner',
    brand: 'Phantom',
    category: 'Shoes',
    musd: 89,
    tag: 'New Drop',
    description: 'Chunky dial-lace sneaker with air-cushion sole. Available in 4 colorways.',
    images: [
      '/products/phantom/phantom.avif',
      '/products/phantom/phantom2.avif',
      '/products/phantom/phantom3.avif',
      '/products/phantom/phantom4.avif',
    ],
    sizes: ['39', '40', '41', '42', '43', '44', '45'],
  },
  {
    id: 2,
    name: 'Savanna Bodycon Dress',
    brand: 'MezoStyle',
    category: 'Dresses',
    musd: 42,
    tag: 'Bestseller',
    description: 'Fitted midi dress with leopard print paneling. Front and back detail shots.',
    images: [
      '/products/Savanna/brown_savanna_1.avif',
      '/products/Savanna/brown_savanna_2.avif',
      '/products/Savanna/black_savanna_1.avif',
      '/products/Savanna/black_savanna_2.avif',
    ],
    colors: ['Brown', 'Black'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
  },
  {
    id: 3,
    name: 'Acrylic Evening Bag',
    brand: 'MezoStyle',
    category: 'Bags',
    musd: 38,
    tag: 'Limited',
    description: 'Structured acrylic clutch for evening occasions.',
    images: [
      '/products/acrylic_evening_bag/apricot.avif',
      '/products/acrylic_evening_bag/lake_blue.avif',
      '/products/acrylic_evening_bag/white_...avif',
    ],
    colors: ['Apricot', 'Lake Blue', 'White'],
  },
  {
    id: 4,
    name: 'Structured Hand Bag',
    brand: 'MezoStyle',
    category: 'Bags',
    musd: 55,
    tag: 'Hot Pick',
    description: 'Bold structured handbag in vibrant colorways.',
    images: [
      '/products/hand_bag/green.avif',
      '/products/hand_bag/purple.avif',
      '/products/hand_bag/red.avif',
    ],
    colors: ['Green', 'Purple', 'Red'],
  },
  {
    id: 5,
    name: 'Chinese Style Dress',
    brand: 'MezoStyle',
    category: 'Dresses',
    musd: 48,
    tag: 'Exclusive',
    description: 'Elegant Chinese-inspired dress with intricate detailing.',
    images: [
      "/products/ladies'_new_chinese_style/black1.avif",
      "/products/ladies'_new_chinese_style/black3.avif",
      "/products/ladies'_new_chinese_style/pink1.avif",
      "/products/ladies'_new_chinese_style/white1.avif",
    ],
    colors: ['Black', 'Pink', 'White'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
  },
  {
    id: 6,
    name: 'Business Casual Shoes',
    brand: 'MezoMen',
    category: 'Shoes',
    musd: 72,
    tag: 'New Drop',
    description: 'Sleek black business casual shoes for the modern professional.',
    images: [
      "/products/men's_business_casual_shoes/black1.avif",
      "/products/men's_business_casual_shoes/black2.avif",
      "/products/men's_business_casual_shoes/black3.avif",
    ],
    sizes: ['39', '40', '41', '42', '43', '44'],
  },
  {
    id: 7,
    name: 'Fashion Work Pants',
    brand: 'MezoMen',
    category: 'Bottoms',
    musd: 35,
    tag: 'Bestseller',
    description: 'Tailored work pants in versatile colorways.',
    images: [
      "/products/men's_fashion_work_pants/black1.avif",
      "/products/men's_fashion_work_pants/black2.avif",
      "/products/men's_fashion_work_pants/apricot1.avif",
      "/products/men's_fashion_work_pants/dark_gray1.avif",
    ],
    colors: ['Black', 'Apricot', 'Dark Gray'],
    sizes: ['28', '30', '32', '34', '36'],
  },
  {
    id: 8,
    name: "Men's Classic Jeans",
    brand: 'MezoMen',
    category: 'Bottoms',
    musd: 44,
    tag: 'Hot Pick',
    description: 'Classic straight-cut blue denim jeans.',
    images: [
      "/products/men's_jeans/blue.avif",
      "/products/men's_jeans/blue2.avif",
      "/products/men's_jeans/blue3.avif",
    ],
    sizes: ['28', '30', '32', '34', '36'],
  },
  {
    id: 9,
    name: 'Straight Leg Sweatpants',
    brand: 'MezoMen',
    category: 'Bottoms',
    musd: 28,
    tag: 'New Drop',
    description: 'Comfortable straight-leg sweatpants in multiple colors.',
    images: [
      "/products/men's_new_straight_leg_sweatpants /beige.avif",
      "/products/men's_new_straight_leg_sweatpants /black1.avif",
      "/products/men's_new_straight_leg_sweatpants /brick_red1.avif",
    ],
    colors: ['Beige', 'Black', 'Brick Red'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
  },
  {
    id: 10,
    name: 'Short Sleeve T-Shirt',
    brand: 'MezoMen',
    category: 'Tops',
    musd: 18,
    tag: 'Bestseller',
    description: 'Clean white short sleeve tee, everyday essential.',
    images: [
      "/products/men's_short_sleeve_t-shirt/white1.avif",
      "/products/men's_short_sleeve_t-shirt/white2.avif",
    ],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
  },
  {
    id: 11,
    name: 'Versatile Casual Shoes',
    brand: 'MezoMen',
    category: 'Shoes',
    musd: 65,
    tag: 'Limited',
    description: 'Minimalist casual shoes in beige and black.',
    images: [
      "/products/men's_versatile_casual_shoes/beige1.avif",
      "/products/men's_versatile_casual_shoes/beige2.avif",
      "/products/men's_versatile_casual_shoes/black1.avif",
      "/products/men's_versatile_casual_shoes/black2.avif",
    ],
    colors: ['Beige', 'Black'],
    sizes: ['39', '40', '41', '42', '43', '44'],
  },
  {
    id: 12,
    name: 'Water-Washed Jeans',
    brand: 'MezoMen',
    category: 'Bottoms',
    musd: 52,
    tag: 'Exclusive',
    description: 'Vintage-washed denim in three distressed colorways.',
    images: [
      "/products/men's_water-washed_jeans/vintage_blue1.avif",
      "/products/men's_water-washed_jeans/vintage_blue2.avif",
      "/products/men's_water-washed_jeans/deep_gray.avif",
      "/products/men's_water-washed_jeans/deep_nostalgia1.avif",
    ],
    colors: ['Vintage Blue', 'Deep Gray', 'Deep Nostalgia'],
    sizes: ['28', '30', '32', '34', '36'],
  },
  {
    id: 13,
    name: 'Casual Shoe',
    brand: 'MezoMen',
    category: 'Shoes',
    musd: 58,
    tag: 'New Drop',
    description: 'Everyday casual shoe in black and brown.',
    images: [
      '/products/men_casual_shoe/black1.avif',
      '/products/men_casual_shoe/black2.avif',
      '/products/men_casual_shoe/brown1.avif',
      '/products/men_casual_shoe/brown2.avif',
    ],
    colors: ['Black', 'Brown'],
    sizes: ['39', '40', '41', '42', '43', '44'],
  },
  {
    id: 14,
    name: 'Mid Print Shirt',
    brand: 'MezoMen',
    category: 'Tops',
    musd: 32,
    tag: 'Hot Pick',
    description: 'Relaxed-fit printed shirt in three colorways.',
    images: [
      '/products/men_mid_print_shirt/burgundy1.avif',
      '/products/men_mid_print_shirt/burgundy2.avif',
      '/products/men_mid_print_shirt/light_blue1.avif',
      '/products/men_mid_print_shirt/light_yellow1.avif',
    ],
    colors: ['Burgundy', 'Light Blue', 'Light Yellow'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
  },
  {
    id: 15,
    name: 'Classic Red Shirt',
    brand: 'MezoMen',
    category: 'Tops',
    musd: 25,
    tag: 'Bestseller',
    description: 'Bold red casual shirt.',
    images: [
      '/products/men_shirt/red1.avif',
      '/products/men_shirt/red2.avif',
    ],
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 16,
    name: 'British Retro Athletic Shoes',
    brand: 'MezoMen',
    category: 'Shoes',
    musd: 78,
    tag: 'Limited',
    description: 'Retro-inspired athletic shoes with British styling.',
    images: [
      "/products/mens_british _retro_casual_athletic_men's_shoes/black1.avif",
      "/products/mens_british _retro_casual_athletic_men's_shoes/black2.avif",
      "/products/mens_british _retro_casual_athletic_men's_shoes/black3.avif",
      "/products/mens_british _retro_casual_athletic_men's_shoes/black4.avif",
    ],
    sizes: ['39', '40', '41', '42', '43', '44'],
  },
  {
    id: 17,
    name: 'Denim Long Pants',
    brand: 'MezoMen',
    category: 'Bottoms',
    musd: 46,
    tag: 'New Drop',
    description: 'Classic denim long pants in multiple washes.',
    images: [
      '/products/mens_denim_long_pants/black1.avif',
      '/products/mens_denim_long_pants/light_blue.avif',
      '/products/mens_denim_long_pants/nolstagic_color1.avif',
    ],
    colors: ['Black', 'Light Blue', 'Nostalgic'],
    sizes: ['28', '30', '32', '34', '36'],
  },
  {
    id: 18,
    name: 'Lightweight Polyester Shirt',
    brand: 'MezoMen',
    category: 'Tops',
    musd: 22,
    tag: 'Bestseller',
    description: 'Breathable lightweight shirt for warm weather.',
    images: [
      '/products/mens_lightweight_polyester_shirt/white1.avif',
      '/products/mens_lightweight_polyester_shirt/white2.avif',
      '/products/mens_lightweight_polyester_shirt/black1.avif',
      '/products/mens_lightweight_polyester_shirt/linen.avif',
    ],
    colors: ['White', 'Black', 'Linen'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
  },
  {
    id: 19,
    name: 'Slip-On Slippers',
    brand: 'MezoMen',
    category: 'Shoes',
    musd: 30,
    tag: 'Hot Pick',
    description: 'Comfortable slip-on slippers in black and camel.',
    images: [
      '/products/mens_slip_on_slippers/black1.avif',
      '/products/mens_slip_on_slippers/black2.avif',
      '/products/mens_slip_on_slippers/camel1.avif',
      '/products/mens_slip_on_slippers/camel2.avif',
    ],
    colors: ['Black', 'Camel'],
    sizes: ['39', '40', '41', '42', '43', '44'],
  },
  {
    id: 20,
    name: 'Suede Velvet T-Shirt',
    brand: 'MezoMen',
    category: 'Tops',
    musd: 28,
    tag: 'Exclusive',
    description: 'Premium suede velvet short sleeve tee in 4 colors.',
    images: [
      '/products/mens_suede_elvet_short_sleeve_t-Shirt/black1.avif',
      '/products/mens_suede_elvet_short_sleeve_t-Shirt/blue1.avif',
      '/products/mens_suede_elvet_short_sleeve_t-Shirt/brown1.avif',
      '/products/mens_suede_elvet_short_sleeve_t-Shirt/pink1.avif',
    ],
    colors: ['Black', 'Blue', 'Brown', 'Pink'],
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 21,
    name: 'Summer Linen Shirt',
    brand: 'MezoMen',
    category: 'Tops',
    musd: 26,
    tag: 'New Drop',
    description: 'Relaxed summer shirt, perfect for warm days.',
    images: [
      '/products/mens_summer_shirt/white1.avif',
      '/products/mens_summer_shirt/white2.avif',
      '/products/mens_summer_shirt/white3.avif',
      '/products/mens_summer_shirt/white4.avif',
    ],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
  },
  {
    id: 22,
    name: 'Mermaid Skirt',
    brand: 'MezoStyle',
    category: 'Bottoms',
    musd: 38,
    tag: 'Limited',
    description: 'Elegant mermaid-cut skirt with flowing silhouette.',
    images: [
      '/products/mermaid_skirt/skirt1.avif',
      '/products/mermaid_skirt/skirt2.avif',
      '/products/mermaid_skirt/skirt3.avif',
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
  },
  {
    id: 23,
    name: 'Midi Dress',
    brand: 'MezoStyle',
    category: 'Dresses',
    musd: 45,
    tag: 'Bestseller',
    description: 'Versatile midi dress in beige and green.',
    images: [
      '/products/midi_dress /beige1.avif',
      '/products/midi_dress /beige2.avif',
      '/products/midi_dress /green1.avif',
      '/products/midi_dress /green2.avif',
    ],
    colors: ['Beige', 'Green'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
  },
  {
    id: 24,
    name: 'Retro Acid Wash Jeans',
    brand: 'MezoStyle',
    category: 'Bottoms',
    musd: 55,
    tag: 'Exclusive',
    description: 'Vintage acid-wash denim with retro appeal.',
    images: [
      '/products/retro_acid_wash_jeans/1.avif',
      '/products/retro_acid_wash_jeans/2.avif',
      '/products/retro_acid_wash_jeans/3.avif',
    ],
    sizes: ['28', '30', '32', '34', '36'],
  },
  {
    id: 25,
    name: 'Satin Shirt',
    brand: 'MezoStyle',
    category: 'Tops',
    musd: 34,
    tag: 'Hot Pick',
    description: 'Luxurious satin shirt with a silky finish.',
    images: [
      '/products/satin_shirt/shirt1.avif',
      '/products/satin_shirt/shirt2.avif',
      '/products/satin_shirt/shirt3.avif',
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
  },
  {
    id: 26,
    name: 'Stand Collar Shirt',
    brand: 'MezoStyle',
    category: 'Tops',
    musd: 29,
    tag: 'New Drop',
    description: 'Spring shirt with elegant stand collar.',
    images: [
      '/products/shirt_with_stand_collar/spring_shirt1.avif',
      '/products/shirt_with_stand_collar/spring_shirt2.avif',
      '/products/shirt_with_stand_collar/spring_shirt3.avif',
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
  },
  {
    id: 27,
    name: 'Stiletto Heels',
    brand: 'MezoStyle',
    category: 'Shoes',
    musd: 68,
    tag: 'Limited',
    description: 'Elegant stiletto heels in gold and silver.',
    images: [
      '/products/stiletto/golden1.avif',
      '/products/stiletto/golden2.avif',
      '/products/stiletto/golden3.avif',
      '/products/stiletto/silver1.avif',
      '/products/stiletto/silver2.avif',
    ],
    colors: ['Gold', 'Silver'],
    sizes: ['35', '36', '37', '38', '39', '40'],
  },
  {
    id: 28,
    name: 'Textured Tote Bag',
    brand: 'MezoStyle',
    category: 'Bags',
    musd: 62,
    tag: 'Bestseller',
    description: 'Structured textured tote in four neutral tones.',
    images: [
      '/products/textured_tote_bag/black1.avif',
      '/products/textured_tote_bag/gray.avif',
      '/products/textured_tote_bag/white.avif',
      '/products/textured_tote_bag/wine.avif',
    ],
    colors: ['Black', 'Gray', 'White', 'Wine'],
  },
  {
    id: 29,
    name: 'Trendy Bag',
    brand: 'MezoStyle',
    category: 'Bags',
    musd: 48,
    tag: 'Hot Pick',
    description: 'On-trend bag in black, blue, and white.',
    images: [
      '/products/trendy_bag/black.avif',
      '/products/trendy_bag/black2.avif',
      '/products/trendy_bag/blue.avif',
      '/products/trendy_bag/white_1.avif',
    ],
    colors: ['Black', 'Blue', 'White'],
  },
  {
    id: 30,
    name: 'Unisex White Sneaker',
    brand: 'MezoStyle',
    category: 'Shoes',
    musd: 55,
    tag: 'Bestseller',
    description: 'Clean unisex white sneaker, a wardrobe staple.',
    images: [
      '/products/unisex_white_shoe/white_shoe.avif',
      '/products/unisex_white_shoe/white_shoe2.avif',
      '/products/unisex_white_shoe/white_shoe3.avif',
    ],
    sizes: ['36', '37', '38', '39', '40', '41', '42', '43'],
  },
  {
    id: 31,
    name: 'Women Dress',
    brand: 'MezoStyle',
    category: 'Dresses',
    musd: 40,
    tag: 'New Drop',
    description: 'Flowy women dress in apricot and green.',
    images: [
      '/products/women_dress/apricot1.avif',
      '/products/women_dress/apricot2.avif',
      '/products/women_dress/dark_green1.avif',
      '/products/women_dress/green1.avif',
    ],
    colors: ['Apricot', 'Dark Green', 'Green'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
  },
  {
    id: 32,
    name: 'Fashion Coat',
    brand: 'MezoStyle',
    category: 'Coats',
    musd: 95,
    tag: 'Exclusive',
    description: 'Stylish women fashion coat in three bold colors.',
    images: [
      '/products/women_fashion_coat/black1.avif',
      '/products/women_fashion_coat/black2.avif',
      '/products/women_fashion_coat/burgundy1.avif',
      '/products/women_fashion_coat/rust.avif',
    ],
    colors: ['Black', 'Burgundy', 'Rust'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
  },
  {
    id: 33,
    name: 'Packet Shirt',
    brand: 'MezoStyle',
    category: 'Tops',
    musd: 24,
    tag: 'Hot Pick',
    description: 'Casual packet shirt in burgundy and orange.',
    images: [
      '/products/women_packet_shirt/burgundy_1.avif',
      '/products/women_packet_shirt/burgundy_2.avif',
      '/products/women_packet_shirt/orange1.avif',
      '/products/women_packet_shirt/orange2.avif',
    ],
    colors: ['Burgundy', 'Orange'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
  },
  {
    id: 34,
    name: 'Teddy Plaid Coat',
    brand: 'MezoStyle',
    category: 'Coats',
    musd: 88,
    tag: 'Limited',
    description: 'Cozy plaid teddy coat with patched pockets.',
    images: [
      '/products/women_plaid_print_patched_pockets_teddy_coat/black1.avif',
      '/products/women_plaid_print_patched_pockets_teddy_coat/pink1.avif',
      '/products/women_plaid_print_patched_pockets_teddy_coat/red1.avif',
    ],
    colors: ['Black', 'Pink', 'Red'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
  },
  {
    id: 35,
    name: 'Women Sandal',
    brand: 'MezoStyle',
    category: 'Shoes',
    musd: 42,
    tag: 'Bestseller',
    description: 'Elegant women sandal in black, camel, and white.',
    images: [
      '/products/women_sandal/black1.avif',
      '/products/women_sandal/black2.avif',
      '/products/women_sandal/camel1.avif',
      '/products/women_sandal/white1.avif',
    ],
    colors: ['Black', 'Camel', 'White'],
    sizes: ['35', '36', '37', '38', '39', '40'],
  },
  {
    id: 36,
    name: 'Satin Slip Dress',
    brand: 'MezoStyle',
    category: 'Dresses',
    musd: 52,
    tag: 'Exclusive',
    description: 'Luxurious satin slip dress in apricot, black, and burgundy.',
    images: [
      '/products/women_satin/apricot1.avif',
      '/products/women_satin/apricot2.avif',
      '/products/women_satin/black_1.avif',
      '/products/women_satin/burgundy.avif',
    ],
    colors: ['Apricot', 'Black', 'Burgundy'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
  },
  {
    id: 37,
    name: 'Sexy Home Pajama',
    brand: 'MezoStyle',
    category: 'Loungewear',
    musd: 32,
    tag: 'Hot Pick',
    description: 'Comfortable and stylish home pajama set.',
    images: [
      '/products/women_sexy_home_pajama /black1.avif',
      '/products/women_sexy_home_pajama /black2.avif',
      '/products/women_sexy_home_pajama /green1.avif',
      '/products/women_sexy_home_pajama /green2.avif',
    ],
    colors: ['Black', 'Green'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
  },
  {
    id: 38,
    name: 'Short Pajamas',
    brand: 'MezoStyle',
    category: 'Loungewear',
    musd: 26,
    tag: 'New Drop',
    description: 'Cute short pajama set in red.',
    images: [
      '/products/women_short_pajamas/red_pajamas_1.avif',
      '/products/women_short_pajamas/red_pajamas_2.avif',
    ],
    colors: ['Red'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
  },
];

// All unique categories
export const CATEGORIES = ['All', ...Array.from(new Set(PRODUCTS.map(p => p.category)))];

// Helper to get product by id
export function getProduct(id: number) {
  return PRODUCTS.find(p => p.id === id);
}
